import Head from 'next/head'
import Image from 'next/image'
import { Inter } from '@next/font/google'
import qrcode from '../public/image-qr-code.png'

const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className='bg-blue-200 min-h-screen p-10' >
        <div className=' mx-10 flex flex-col bg-white'>
 
        <Image className='p-2 w-md h-md ' src={qrcode} alt=''/>
        <h1>Improve your front-end skills by building projects</h1>
        <p>Scan the QR code to visit Frontend Mentor and 
          take your coding skills to the next level
        </p>
        
        </div>
      </main>
    </>
  )
}
